### ISSUE TITLE
Modern interface and build_release

### ISSUE THREAD

**Issue by jinzo** [traccar/traccar-web#1016]
Hi,

in commit https://github.com/traccar/traccar-web/commit/5f86dec31528d8c06608e1a37ac5529bca91ad78 the build_release script was removed from the modern package. I searched and did not find any explanation as to why? I know, that per the documentation it is not advisable to run traccar in a subdirectory, but this is something I would like to do for a limited time period for easier migration from the old interface to the new interface. Did it cause any problems or is it generally safe to use?

Either way, the documentation at https://www.traccar.org/build-web-app/ should be updated to reflect the change.

P.S: Is there a preferred way to communicate documentation bugs/improvements? I'm not sure if opening a bug report here is the correct way :)

**Comment by tananaev** [comment]
The reason is that now modern app is run in the root path by default, so we don't need two different commands.

You should be still be able to use it in a subdirectory if you want to. No major issues, but you need to make sure links in the templates are correct, like password reset link.

Documentation updated. Thanks for pointing it out.

It's ok to create a bug tickets here if it's definitely an issue. You can also just post it on the forum.
