### ISSUE TITLE
calendarid not exist in datasbase

### ISSUE THREAD

**Issue by al-moallem** [traccar/traccar-web#1175]
when I want to add a new device from modern web interface I got this error :

ERROR: column "calendarid" of relation "tc_devices" does not exist Position: 40 - PSQLException

both backend and web are 5.8 version

**Comment by tananaev** [comment]
It's interesting because the column was added after 5.8, so I think you're not using the official version 5.8. You're probably just using the latest code.

**Comment by al-moallem** [comment]
First, thank you for this rapid response.
Second, I cloned master branch. Is this different from release 5.8 ?

**Comment by tananaev** [comment]
Is this your first time working with GitHub? Yes, the master branch is of course not the same thing as the latest official release. Master branch includes all the work in progress changes, many of which will make it incompatible with the old database. That's why in [our documentation](https://www.traccar.org/source-code/) we say that we don't recommend using master and you should use the stable version tags instead.

**Comment by al-moallem** [comment]
Yes, you are right. That was my mistake. Thank you for your help.
