### ISSUE TITLE
How to compile traccar web

### ISSUE THREAD

**Issue by leovicio** [traccar/traccar-web#28]
How to build web traccar
Eclipse or Netbeans?
Which plugins need to install?
and how important the project?

**Comment by bizkit1** [comment]
Got traccar, importedto netbeans, build whn starting it gives me this in wrapper log:

STATUS | wrapper  | 2015/06/19 22:36:01 | Launching a JVM...
INFO   | jvm 1    | 2015/06/19 22:36:01 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperSimpleApp Error: Unable to locate the class org.traccar.Main : java.lang.ClassNotFoundException: org.traccar.Main
INFO   | jvm 1    | 2015/06/19 22:36:02 | 
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperSimpleApp Usage:
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperManager Error: Error in WrapperListener.start callback.  java.lang.IllegalArgumentException: can't parse argument number: app_class{/app_method}
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperManager Error: java.lang.IllegalArgumentException: can't parse argument number: app_class{/app_method}
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperManager Error: 	at java.text.MessageFormat.makeFormat(Unknown Source)
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperManager Error: 	at java.text.MessageFormat.applyPattern(Unknown Source)
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperManager Error: 	at java.text.MessageFormat.<init>(Unknown Source)
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperManager Error: 	at java.text.MessageFormat.format(Unknown Source)
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperManager Error: 	at org.tanukisoftware.wrapper.WrapperResources.getString(WrapperResources.java:194)
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperManager Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.showUsage(WrapperSimpleApp.java:597)
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperManager Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.start(WrapperSimpleApp.java:441)
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperManager Error: 	at org.tanukisoftware.wrapper.WrapperManager$10.run(WrapperManager.java:4163)
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperManager Error: Caused by: java.lang.NumberFormatException: For input string: "app_class{/app_method}"
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperManager Error: 	at java.lang.NumberFormatException.forInputString(Unknown Source)
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperManager Error: 	at java.lang.Integer.parseInt(Unknown Source)
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperManager Error: 	at java.lang.Integer.parseInt(Unknown Source)
INFO   | jvm 1    | 2015/06/19 22:36:02 | WrapperManager Error: 	... 8 more

**Comment by tananaev** [comment]
Looks like there is some problem with wrapper config file.

**Comment by bizkit1** [comment]
if i put the original tracker-server.jar it works, but when i compile it myself, te service starts, but i can't access the website and i get that error in the log. Any ideea what i must check in the wrapper file? Or any ideea when we will find a generated up-to-dated jar on your website? Thanks!

**Comment by tananaev** [comment]
There were significant changes since last version, so you can't use old config with the version you built from source.
