### ISSUE TITLE
maps

### ISSUE THREAD

**Issue by netluca1** [traccar/traccar-web#408]
Hello,
you can move from one map to another without exiting the program?
how it was done in WEB UI version of Livtak?
![immagine](https://cloud.githubusercontent.com/assets/23439828/22999716/4101d40c-f3dd-11e6-85be-63ee6d9dd2a7.jpg)

**Comment by tananaev** [comment]
Already answered in https://github.com/tananaev/traccar/issues/2918#issuecomment-280169307.

**Comment by netluca1** [comment]
yes but is more simple use the button for select

**Comment by tananaev** [comment]
It is, but how often does user change map layers? I don't see much value in it.

**Comment by netluca1** [comment]
i have ask at more client and reply is more facility use a button for select.
is possible integrate?

**Comment by tananaev** [comment]
Send me an email to discuss it.

**Comment by Jeferex** [comment]
Hi @tananaev, I already updated my traccar and I miss this feature. In old traccar-web it was easier to change map layers. Some maps show more accurate info in my country.

**Comment by tananaev** [comment]
@Jeferex, it's still possible to change maps.

**Comment by Jeferex** [comment]
I know but now, if I want to change map layer, I have to go to Settings > Account > Preference > choose Map layer, save and refresh. Many steps to do one simple thing.

**Comment by Tegu** [comment]
I agree, there are quite a few steps. My main use for quick layer switching would be switching between the world map and a custom map that exists only in a limited area. This use case is actually related to issue #563. I think having a layer switcher would lessen the need for a fallback map.

Additionally, refreshing reverts the view back to the default. For example, this prevents switching between the map and satellite view quickly. Of course, a workaround would be to save the current view before switching layers, but that would lose the old (perhaps well centered) default and add an additional step.

Apparently, OpenLayers 3 nor 4 do not have a built-in layer switcher. There seems to be at least some third party library for that purpose (https://github.com/walkermatt/ol3-layerswitcher) but I have not looked into it. However, as there seem to be some plans for a new website in #592, Leaflet does have a layer switcher (http://leafletjs.com/examples/layers-control/).

After all, I must admit that the issue is rather minor.

**Comment by tananaev** [comment]
This is already supported in both apps.
