### ISSUE TITLE
Cannot GET /api/server

### ISSUE THREAD

**Issue by gnkafridi** [traccar/traccar-web#673]
GOT THIS ERROR:
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/server</pre>
</body>
</html>
```

**Comment by abkiran** [comment]
You need read basics of traccar from the documentation again.

You can ping me on kirancse123@gmail.com
I'll help u understand

**Comment by abkiran** [comment]
Please follow the documentation available at traccar.org

**Comment by mohamedfadol** [comment]
hi guys can inform me how solve it pls

**Comment by abkiran** [comment]
I looked at this long ago, I don't have any details now

**Comment by mohamedfadol** [comment]
thnks alot @abkiran  for reply

**Comment by mohamedfadol** [comment]
do you have any suggest about this error  => Request URL: https://localhost/gps/server?_doc=1599143319508 result 404

**Comment by tananaev** [comment]
Why is path `/gps/server` instead of `/api/server`?

**Comment by mohamedfadol** [comment]
i made sub-domain to redirect on server

**Comment by tananaev** [comment]
Do you mean proxy? Please provide details.

**Comment by mohamedfadol** [comment]
I have a website with a link to the traccar page. The traccar is on a separate server from the domain of the website. I access it by IP, 
 i created a subdomain on the website server in order to get to the traccar ip so that the subdomain shows the name of the
 subdomain instead of the ip on the browser
 my problem 
When I click on the link, an error appears

Note :)  the ip does not have a

**Comment by tananaev** [comment]
How is this related to a URL path and my previous comment?
