### ISSUE TITLE
Question about why compulsory requests are made to traccar.com on v4.11

### ISSUE THREAD

**Issue by est61** [traccar/traccar-web#793]
As mentioned in the wrong repo here: https://github.com/traccar/traccar/issues/4602

When i say compulsory requests, i mean that in previous versions of traccar server, at least in version 4.6 which i was on, i never allowed traccar.com on noscript and yet i was still able to login to my self-hosted server, and everything was fully functional.

Even though you say all version of Traccar require external dependencies, this version 4.11 means i am compelled to accept traccar.com for my self-hosted instance to fully function, this is not right.

Can the mapping and all the dependencies be a part of the self-hosted server and in the hands of the user instead of pulling dependencies from traccar.com?  Our self-hosted servers should not be dependent on traccar.com at all.

Here is how v4.11 doesnt even load the login page unless i allow it explicitly, it will keep spinning forever.
![traccar](https://user-images.githubusercontent.com/56405634/99132079-ab03eb80-261d-11eb-9674-d1166f1de55c.png)

**Comment by tananaev** [comment]
It can definitely be made fully self hosted. The web app never sends any data to external servers. It only downloads dependencies that are not bundled in.

This is the place where we use it for the new web app:

https://github.com/traccar/traccar-web/blob/master/modern/src/map/mapStyles.js

This is the place for the old web app:

https://github.com/traccar/traccar-web/blob/master/web/load.js

Just to reiterate, Traccar always required external dependencies. It's not something new. It's all basically standard JS libraries and resources that the app needs. The new thing is instead of using several external CDN websites, we use our own. It's actually also open source, so you can verify that there's nothing sketchy:

https://github.com/traccar/traccar-cdn

**Comment by est61** [comment]
@tananaev thanks for the clarification.
If its not a lot of trouble, how can you incorporate it into the next version of traccar web app so that its fully independent?

**Comment by tananaev** [comment]
I don't think we have such plans, but contributions are welcome.

**Comment by est61** [comment]
@tananaev sorry but unfortunately i am not that proficient with programming. What is needed to make this fully self-hosted?

**Comment by tananaev** [comment]
Not sure I understand the question. I already explained above what needs to be done.

**Comment by est61** [comment]
Sorry but i dont see you explaining what actually needs to be done to incorporate the code in the self-hosted version.  Im saying, to make it self-hosted, cant you just copy-paste this code https://github.com/traccar/traccar-web/blob/master/modern/src/map/mapStyles.js for example **into** the self-hosted web code and have it self-hosted?  Im asking **what do we technically need to do** to make it self-hosted?

**Comment by tananaev** [comment]
What makes you think that `mapStyles.js` is not already self-hosted? It actually is.

I already explained what needs to be done on the high level. I cannot provide exact step by step guide, of couse.

**Comment by est61** [comment]
> What makes you think that `mapStyles.js` is not already self-hosted? It actually is.

Sorry, i misstated - I meant like for example could you take https://github.com/traccar/traccar-cdn/tree/master/map/fonts and have them stored in the server version and then refer to them straight from there?

**Comment by tananaev** [comment]
Yes, that's exactly what you need to do.
