### ISSUE TITLE
[Modern] Design Issue for Deleting a Device

### ISSUE THREAD

**Issue by mail2bishnoi** [traccar/traccar-web#889]
Hi @dkyeremeh @tananaev 

If we have a device without any positions data in the device list, how to delete that device?

Because without any positions, we don't display a status window on the map.

**Comment by tananaev** [comment]
Very good point. It will apply to everything else we have in that dialog, like editing.

**Comment by dkyeremeh** [comment]
@mail2bishnoi @tananaev Apart from deleting and editing, what other actions can be performed on a device without position data? 

I would like to update the design to add those features

**Comment by dkyeremeh** [comment]
For consistency in behaviour, we can still show the dialog even though it will not have a corresponding icon on the map.

On desktop, the dialog can be displayed next to the item on the device list.

@tananaev @mail2bishnoi what do you think?

**Comment by tananaev** [comment]
It works, but might be tricky to implement. Currently we use map bubble for it.

**Comment by mail2bishnoi** [comment]
I think to have something like in the current web application, on selecting a device activates the buttons on the top bar menu.

**Comment by dkyeremeh** [comment]
I'm not sure how the map bubble works. But is it possible to separate the dialog into a component. if so, we can conditionally include it in the device item and show it when there's no position data.

This will mean that there will be 2 different ways in showing the dialog in terms of code, but that one consistent way in terms of user experience.

The other alternative is to have close and edit icons on the device item on the list when there is no position data. This will take the place of regular icons since no other icons will be likely shown when there's no position data. The downside is that this will create a fragmented user experience

**Comment by tananaev** [comment]
I like the first option.

**Comment by tananaev** [comment]
This is already fixed.
