### ISSUE TITLE
[Modern] About the current web notifications and a new feature

### ISSUE THREAD

**Issue by hieund612** [traccar/traccar-web#892]
Hi Anton and everyone, I have some question about the web notifications in the modern UI.

1. I see that the web notifications for the modern UI are displayed as the browsers' notifications. I use Google Chrome and sometimes, it doesn't show the notifications even after allowing the notifications to appear.

2. In the old UI we have the Ext.Toast. Is it possible to remake the web notifications as Material-UI Snackbars in the new one?

3. I'm thinking of developing a new feature, as we can use heatmap for reports with the devices' coordinates. Have you ever tried to create a heatmap layer supported by Mapbox / MapLibre GL JS?

**Comment by tananaev** [comment]
Do you know why the notification doesn't appear even if it's allowed? Native notifications feel nicer to use, but if there are some issues, I don't mind changing.

As for heatmap, I'm sure there's a solution. Google search gives [this example](https://docs.mapbox.com/mapbox-gl-js/example/heatmap-layer/). Have you tried searching? Never used it though.

**Comment by hieund612** [comment]
1. I don't know, it might be due to the browser. I think we should use Material-UI Snackbars, which are available for all browsers; I'm working on one as well at the moment.

2. Yes, I tried that example but there was nothing. It might be something wrong with the setData function, I guess.

**Comment by tananaev** [comment]
1. We need to find the root cause first. Then we can make an informed decision.

**Comment by lucasleite01** [comment]
Hello, @tananaev and @hieund612.

1. I think I might have founded the root cause of notifications are not being displayed on Google Chrome.

It happens because of OS configuration. In my case, notifications were enabled in Google Chrome for localhost, but disabled in the OS configuration. Searching, I followed the steps described [here](https://www.makeuseof.com/google-chrome-notifications-not-working-fixes/). Number 8 worked for me:

![image](https://user-images.githubusercontent.com/17521730/153483537-d782a2e3-46a9-4152-b268-68530c0199ad.png)

However, during research I looked at [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API) and I came across with this warning:

![image](https://user-images.githubusercontent.com/17521730/153481549-c6252c72-c61c-40ed-88fa-3620de3dd857.png)

Since Traccar web interface could run on not secure context (HTTP), be dependent of [Notifications API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API) could be a limitation and the [Snackbar](https://mui.com/pt/components/snackbars/) implementation suggested by @hieund612 is good idea.

Let us know your decision, Anton.

**Comment by tananaev** [comment]
Can we determine if notifications are on or off? If yes, I suggest we do native notifications but fallback to a snackbar. Does that work?

**Comment by tananaev** [comment]
I guess if it's not possible to tell, I agree with snackbar version.

**Comment by lucasleite01** [comment]
Yeah, the problem relies on the fact we cannot determine if the OS has browser notification enabled. In that way, the user will have to enable browser notification on the OS.

Can we proceed with the snackbar version?

**Comment by lucasleite01** [comment]
> I guess if it's not possible to tell, I agree with snackbar version.

Ok then. I'll work on that.
